[package]
name = "status"
version = "0.1.0"
authors = ["peterlvilim@gmail.com"]
edition = "2018"


[dependencies]
serde = { version = "1.0.96", features = ["derive"] }
serde_json = "1.0.96"
chrono-tz = "0.8.2"
chrono = "0.4.24"
reqwest = { version = "0.11.17", features = ["blocking"] }
